/* v_payments */
create or replace algorithm = merge view v_payments as
select
  id payment_id,
  payorId payor_contact_id,
  paymentInstrument payment_instrument,
  paymentMethodId payment_method_id,
  paymentInterface payment_interface,
  accountName account_name,
  maskedNumber masked_number,
  transactionAmount transaction_amount,
  convenienceFee convenience_fee,
  vendorProcessingFee vendor_processing_fee,
  transactionDateTime transaction_date_time,
  confirmationNumber confirmation_number,
  committer entered_by,
  entryDateTime entry_date_time,
  dateUpdated date_updated,
  invoiceNumber invoice_number,
  checkNumber check_number,
  sweepCheckNumber sweep_check_number,
  authorizationState authorization_state,
  vendorStage vendor_stage,
  vendorStageSuccess vendor_success,
  vendorResponse vendor_response_obj,
  vendorLog vendor_log_obj,
  vendorMessage vendor_message,
  commissionPayment is_commission_payment,
  isAutoPayment is_auto_payment,
  sweep is_sweep_payment,
  complete completed,
  deleted,
  voided,
  nsf,
  printedToDeposit printed_to_deposit,
  selectedOnDeposit selected_on_deposit,
  commPayId commission_payment_id,
  distribution distribution_obj,
  fileIds file_id_list,
  transactionType sale_or_credit,
  externalSystemReference external_system_reference
from payments;
